services:
  db:
    image: postgres:15-alpine
    container_name: tokenizer_db
    restart: always
    environment:
      POSTGRES_USER: api_manager
      POSTGRES_PASSWORD: api_secure_vault_2026
      POSTGRES_DB: TOKENIZER_HUANCAYO
    ports:
      - "5433:5432"
    volumes:
      - tokenizer_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build: .
    container_name: tokenizer_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://api_manager:api_secure_vault_2026@db:5432/TOKENIZER_HUANCAYO
      PORT: 3000
      JWT_SECRET: super_secret_token_2026_informa
      TOKEN_LENGTH: 4
    env_file:
      - .env
    depends_on:
      - db

volumes:
  tokenizer_data:
